import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gradebooks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://18.167.85.68:8100/docs/">Gradebooks</a>
        </h1>

        <p className={styles.description}>
          Get started by checking {" "}
          <a href="http://18.167.85.68:8100/docs/">Gradebooks API</a>
        </p>
      </main>

      
    </div>
  )
}

export default Home
